# Title : Loon_Config
# Author : 废宗·Feizong
# Version : 1.0
# URL : https://github.com/Feizongg/Loon
# Update : 06/29/2026 10:53:28

[General]
ip-mode = v4-only
disable-stun = false
dns-reject-mode = LoopbackIP
domain-reject-mode = DNS
udp-fallback-mode = REJECT
sni-sniffing = true
disconnect-on-policy-change = false
switch-node-after-failure-times = 3
# 跳过某个域名或者IP段
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
# DNS server
# dns服务，system表示系统自带dns服务器
dns-server = system,223.5.5.5,119.29.29.29,1.1.1.1,8.8.8.8
interface-mode = auto
# 是否允许wifi下共享网络
allow-wifi-access = false
# wifi共享开启时http服务的端口
wifi-access-http-port = 7222
# wifi共享开启时socks5服务的端口
wifi-access-socks5-port = 7221
# 节点测速时的url
proxy-test-url = http://www.google.com/generate_204
internet-test-url = http://connectivitycheck.platform.hicloud.com/generate_204
# 节点测速时的超时秒数
test-timeout = 5
# GeoIP
geoip-url = https://github.com/Masaiki/GeoIP2-CN/raw/release/Country.mmdb
ipasn-url = https://raw.githubusercontent.com/P3TERX/GeoLite.mmdb/download/GeoLite2-ASN.mmdb

[Proxy]
# 内置DIRECT、REJECT策略

[Remote Proxy]
# 订阅节点
# 格式别名 = 订阅URL
USA = URL

[Remote Filter]

[Proxy Group]
# 节点选项
# 筛选节点
PROXY = select,USA,DIRECT

[Rule]
# 本地分流
GEOIP,CN,DIRECT
FINAL,PROXY

[Remote Rule]
# URL订阅分流
# 局域网及保留地址直连
https://github.com/Feizongg/Loon/Rule/LAN.list, policy=DIRECT, tag=LAN, enabled=true
# 大陆地区直连（From blackmatrix）
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/ChinaMax/ChinaMax.list, policy=DIRECT, tag=ChinaMax, enabled=true
# 广告拦截（From 秋风）
https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Surge-RULE-SET.list, policy=REJECT, tag=秋风广告拦截, enabled=true
# 广告拦截（From 奶思）
https://github.com/fmz200/wool_scripts/raw/main/Loon/rule/rejectAd.list, policy=REJECT, tag=广告拦截, enabled=true
# 全球分流（From ConnersHua）
https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Proxy.list, policy=PROXY, tag=全球分流, enabled=true
# 抖音分流
https://github.com/Feizongg/Loon/Rule/Douyin.list, policy=PROXY, tag=抖音分流, enabled=false
# 小红书分流
https://github.com/Feizongg/Loon/Rule/RedBook.list, policy=PROXY, tag=小红书分流, enabled=false

[Rewrite]

[Host]

[Script]

[Remote Script]

[Plugin]
# URL订阅插件（可自行寻找各类适配插件，进行去广告等操作）
# Google人机验证（From NobyDa）
https://raw.githubusercontent.com/NobyDa/Script/master/Loon/Loon_Google_CAPTCHA.plugin, enabled=true
# Apple Map(From iRingo)
https://github.com/NSRingo/Maps/releases/latest/download/iRingo.Maps.plugin, enabled=true

[Mitm]
hostname = configuration.ls.apple.com,gspe1-ssl.ls.apple.com,gspe35-ssl.ls.apple.com,gsp-ssl.ls.apple.com,gspe19-ssl.ls.apple.com,gspe12-ssl.ls.apple.com
ca-p12 =
ca-passphrase =
skip-server-cert-verify = false